database:
  conversations_path: data/qa_conversations.db
  knowledge_path: data/qa_knowledge.db
  rag_path: data/qa_intelligence_rag.db
  url: sqlite:///./data/qa_intelligence.db
environment:
  data_directory: data
  environment: development
  logs_directory: logs
interface:
  playground:
    enabled: true
    port: 7777
  terminal:
    enable_markdown: true
    show_tool_calls: true
    streaming:
      enabled: true
      show_cursor: true
      cursor_style: "⚡"
      typing_delay: 0.02
logging:
  enable_file_logging: true
  level: INFO
  log_file: logs/qa_intelligence.log
model:
  id: gpt-5-mini
  provider: openai
  temperature: 1.0
  stream: true
  stream_config:
    enabled: true
    chunk_delay: 0.01  # Delay between chunks in seconds for smooth display
    show_thinking: true  # Show reasoning process in real-time
tools:
  enabled: true
  tools:
  - enabled: false
    name: web_search
  - enabled: false
    name: python_execution
  - enabled: false
    name: file_operations

reasoning:
  enabled: false
  type: agent
