name: Auto-merge develop to main
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          
      - name: Run quality checks
        run: make qa-check
        
      - name: Run tests
        run: make test

  auto-merge:
    needs: quality-check
    runs-on: ubuntu-latest
    if: github.actor == 'stffns' && github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}