name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run linting
      run: |
        make format-check
        make lint
    
    - name: Run type checking
      run: |
        make type-check
    
    - name: Run tests
      run: |
        make test
    
    - name: Run security scan
      run: |
        make security-check

  websocket-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test WebSocket system
      run: |
        python -m pytest src/websocket/tests/ -v
    
    - name: Test QA Agent integration
      run: |
        python -c "from src.websocket.qa_agent_adapter import QAAgentAdapter; print('QA Agent adapter working')"

